### ISSUE TITLE
Can't change colors in the Gamut Mapping Playground 

### ISSUE THREAD

**Issue by lloydk** [color-js/apps#6]
The Gamut Mapping Playground app throws exceptions on initial page load and when trying to change the color.

**Firefox Console Output**
![image](https://github.com/color-js/apps/assets/65072/eb7f8154-b3c7-4814-99c0-e1654e53b42e)

**Comment by facelessuser** [comment]
Yeah, just stumbled on this problem as well when testing out #7.

```
vue.esm-browser.js:9609 Uncaught (in promise) TypeError: Cannot read properties of null (reading '_vei')
    at patchEvent (vue.esm-browser.js:9609:25)
    at patchProp (vue.esm-browser.js:9684:13)
    at patchElement (vue.esm-browser.js:6785:29)
    at processElement (vue.esm-browser.js:6605:13)
    at patch (vue.esm-browser.js:6522:21)
    at patchBlockChildren (vue.esm-browser.js:6831:13)
    at processFragment (vue.esm-browser.js:6893:17)
    at patch (vue.esm-browser.js:6518:17)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7135:17)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
```
